controller_list:
  - name: fake_move_group_controller
    type: $(arg fake_execution_type)
    joints:
      - motortom2m
      - joint2
      - joint4
      - joint6
      - end
initial:  # Define initial robot poses per group
  - group: move_group
    pose: init